name: test

on:
  push:
  schedule:
    - cron: '0 0 * */1 *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3, 8.4]
    name: PHP ${{ matrix.php-version }}
    steps:
      - name: Install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, calendar
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maintain Composer cache
        uses: actions/cache@v4
        with:
          path: .cache/composer
          key: composer-${{ hashFiles('composer.json') }}
          restore-keys: composer-
      - name: Install packages
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just install
      - run: just test
