name: test

on:
  push:
  schedule:
    - cron: '0 0 * */1 *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3]
    name: PHP ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, calendar
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maintain Composer cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json') }}
          restore-keys: composer-
      - name: Install packages
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make install
      - run: make test
